name: 'Phx Build And Deploy Composite Action'
description: 'Execute Build And Deploy Operations In A Composite Action'
inputs:
  secrets:
    description: 'Secrets'
    required: true
  actionInputs:
    description: 'Inputs'
    required: true
  is-enterprise-app-build:
    type: boolean
    description: Enterprise App Build
    required: true
  enable-extended-ops:
    type: boolean
    description: Enable Extended Ops
outputs:
  json-action-outputs:
    description: "Json Composite Action Outputs"
    value: ${{ toJSON(steps.json-ops.outputs) }}
  json-action-extended-outputs:
    description: "Json Composite Action Outputs"
    value: ${{ toJSON(steps.json-extended-ops.outputs) }}    
  has-extended-outputs:
    description: "Has Json Extended Composite Action Outputs"
    value: ${{ steps.json-extended-ops.outputs.has-extended-ops-results || false }}

    
runs:
  using: "composite"
  steps:
    - name: Set Env Inputs
      shell: bash
      run: |
          echo "RUN_SECRET_SECRET1=${{ fromJSON(inputs.secrets).DESC }}" >> $GITHUB_ENV  
