name: 'Faux Composite Action'
description: 'Execute Build And Deploy Operations In A Composite Action'
inputs:
  secrets:
    description: 'Secrets'
    required: true
  actionInputs:
    description: 'Inputs'
    required: true
  is-enterprise-app-build:
    type: boolean
    description: Enterprise App Build
    required: true
  enable-extended-ops:
    type: boolean
    description: Enable Extended Ops

    
runs:
  using: "composite"
  steps:
    - name: Set Env Inputs
      shell: bash
      run: |
          echo "Composite Workspace Folder: ${{github.workspace}}"
