name: 'Faux Composite Action'
description: 'Execute Build And Deploy Operations In A Composite Action'
inputs:
  app:
    description: App Distribution Id
    required: true
  token:
    description: Token
    required: true
  file:
    description: Package
    required: true
  release-notes:
    description: Change Log
    required: true
  group:
    description: App Group
    
runs:
  using: "composite"
  steps:
    - name: Set Env Inputs
      shell: bash
      run: |
          echo "App: ${{inputs.app}}"
          echo "Token: ${{inputs.token}}"
          echo "Package: ${{inputs.file}}"
          echo "Change Log: ${{inputs.release-notes}}"
          echo "Group: ${{inputs.group}}"
